export const GEAR_PREFIX = 'gear:item:';
const IMAGE_TYPES = new Map([['image/jpeg','jpg'],['image/png','png'],['image/webp','webp'],['image/avif','avif']]);
export class GearRequestError extends Error { constructor(message,status=400){super(message);this.status=status;} }
const text=(form,name)=>{const value=form.get(name);return typeof value==='string'?value:''};
export const readPayload=async(request)=>{if(!(request.headers.get('Content-Type')||'').includes('multipart/form-data'))throw new GearRequestError('Use multipart form data.',415);let form;try{form=await request.formData()}catch{throw new GearRequestError('Invalid form data.')};const field=form.get('image');return{id:text(form,'id'),name:text(form,'name'),category:text(form,'category'),owner:text(form,'owner'),rating:text(form,'rating'),description:text(form,'description'),kitParts:text(form,'kitParts'),imageAlt:text(form,'imageAlt'),image:field&&typeof field==='object'&&field.size>0?field:null}};
export const validateMetadata=(payload)=>{const name=payload.name.trim().replace(/\s+/g,' ');const owner=typeof payload.owner==='string'?payload.owner.trim():'';if(!['','Jet Sullivan','Ben Stapleton','Jet Sullivan & Ben Stapleton'].includes(owner))throw new GearRequestError('Choose Jet, Ben, or shared ownership.');const category=payload.category.trim().replace(/\s+/g,' ');const description=payload.description.trim();const imageAlt=payload.imageAlt.trim().replace(/\s+/g,' ');const rating=Number(payload.rating);const kitParts=payload.kitParts.split(/\r?\n/).map(x=>x.trim().replace(/\s+/g,' ')).filter(Boolean);if(!name||name.length>120)throw new GearRequestError('Gear name must be between 1 and 120 characters.');if(!category||category.length>80)throw new GearRequestError('Choose a category of 80 characters or fewer.');if(!description||description.length>20000)throw new GearRequestError('Description must be between 1 and 20,000 characters.');if(!Number.isFinite(rating)||rating<.5||rating>5||(rating*2)%1)throw new GearRequestError('Rating must be between 0.5 and 5 in half-star steps.');if(imageAlt.length>180)throw new GearRequestError('Photo description must be 180 characters or fewer.');if(kitParts.length>100||kitParts.some(x=>x.length>200))throw new GearRequestError('Use no more than 100 kit parts, each under 200 characters.');return{name,category,owner,rating,description,kitParts,imageAlt:imageAlt||(owner?`${name} owned by ${owner}`:name)}};
export const validateImage=(file,{required=false}={})=>{if(!file){if(required)throw new GearRequestError('Choose a product photo.');return null}const type=String(file.type||'').toLowerCase();const extension=IMAGE_TYPES.get(type);if(!extension)throw new GearRequestError('Images must be JPEG, PNG, WebP, or AVIF.',415);if(file.size<=0||file.size>15*1024*1024)throw new GearRequestError('Images must be no larger than 15 MB.',413);return{file,type,extension}};
export const putImage=async(env,id,image)=>{if(!env.MEDIA_BUCKET)throw new GearRequestError('MEDIA_BUCKET binding is missing.',503);const key=`team-gear-${Date.now()}-${crypto.randomUUID()}.${image.extension}`;await env.MEDIA_BUCKET.put(key,image.file.stream(),{httpMetadata:{contentType:image.type},customMetadata:{entryId:id,section:'gear',originalName:image.file.name.slice(0,180)}});return{imageKey:key,imageType:image.type}};
export const listItems=async(kv)=>{const keys=[];let cursor;do{const result=await kv.list({prefix:GEAR_PREFIX,limit:1000,...(cursor?{cursor}:{})});keys.push(...(result.keys||[]));cursor=result.list_complete===false?result.cursor:undefined}while(cursor);const items=await Promise.all(keys.map(key=>kv.get(key.name,'json')));return items.filter(Boolean).sort((a,b)=>String(a.category).localeCompare(String(b.category))||String(a.name).localeCompare(String(b.name)))};
export const readItem=(kv,id)=>kv.get(`${GEAR_PREFIX}${id}`,'json');
export const writeItem=(kv,item)=>kv.put(`${GEAR_PREFIX}${item.id}`,JSON.stringify(item));
export const removeItem=(kv,id)=>kv.delete(`${GEAR_PREFIX}${id}`);
export const responseItem=(item)=>({id:String(item.id||''),name:String(item.name||''),category:String(item.category||'Gear'),owner:String(item.owner||''),rating:Number(item.rating)||0,description:String(item.description||''),kitParts:Array.isArray(item.kitParts)?item.kitParts:[],imageAlt:String(item.imageAlt||''),imageUrl:item.imageKey?`/api/media/${encodeURIComponent(item.imageKey)}`:null,createdAt:String(item.createdAt||''),updatedAt:String(item.updatedAt||'')});
export const json=(body,init={})=>Response.json(body,{...init,headers:{'Cache-Control':'no-store',...(init.headers||{})}});
